name: Deploy fixes to other versions with rebase main

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  deploy-subversions:
    uses: Odoo-Ninjas/git-workflows/.github/workflows/deploy_to_subversions.yml@v5
    with:
      branches: "14.0:main 15.0:main 16.0:main ||| 17.0:16.0 || 13.0:14.0"

